#!/usr/bin/env bash

# battery: print the mac battery health information
# Author: Nkululeko Jonas
# Date: 26-02-2025

# Get battery health info 
battery_info=$(system_profiler SPPowerDataType | grep -A 20 "Battery Information")
health=$(echo "$battery_info" | grep "Condition" | awk -F': ' '{print $2}')
cycle_count=$(echo "$battery_info" | grep "Cycle Count" | awk '{print $3}')
max_capacity=$(echo "$battery_info" | grep "Maximum Capacity" | awk '{print $3}')

# Report battery information
echo "Cycle Count: $cycle_count"
echo "Maximum Capacity: $max_capacity"
echo "Battery Health: $health"
