#!/usr/bin/env bash

# dns-flush: flush my DNS settings on mac
# Author: Nkululeko Jonas
# Date: 26-02-2025

# Restart MacOS DNSResponder
sudo killall -HUP mDNSResponder && echo "mDNSResponder has been restarted successfully."
