#!/usr/bin/env bash

# empty: empty a directory if it exists
# Author: Nkululeko Jonas
# Date: 26-02-2025

# Validate arguments
if [[ $# -ne 1 ]]; then
    echo "Usage: $(basename "$0") <directory>"
    exit 1
fi

DIR="$1"

# Attempt to empty directory
if [[ -d "$DIR" ]]; then
    rm -rf "${DIR:?}"/*
    echo "Emptied $DIR"
else
    echo "Error: Directory '$DIR' does not exist"
    exit 1
fi 
