#!/bin/bash

# longest: find the longest file with given extension
# Author: Nkululeko Jonas
# License: MIT
set -euo pipefail

# Count the lines of all the file with extension provided
# Sort them and give me the longest line
wc -l "$1"/*."$2" | sort -n | tail -n 1
