#!/usr/bin/env bash

# Change into approp dir
cd "$1" || exit 1

# Count the lines of all the file with extention provided
# Sort them and give me the longest line
wc -l ./*."$2" | sort -n | tail -n 1
