#!/bin/bash

# netcheck: ping a website (google) and check return status for connection 
# Author: Nkululeko Jonas
# License: MIT

# Check the system for internet via ping
check_internet() {
    ping -c 1 google.com >/dev/null 2>&1
    return $?
}
