#!/usr/bin/env bash

# netcheck: ping a website (google) and check return status for connection 
# Author: Nkululeko Jonas
# Date: 25-01-2025

# Check the system for internet via ping
check_internet() {
    ping -c 1 google.com >/dev/null 2>&1
    return $?
}
