#!/usr/bin/env bash

# search: search a directory for a string
# Author: Nkululeko Jonas
# Date: 22-01-2025

# use -iru to search directories ack usually ignores (like .git)
if [ -x /usr/bin/ack-grep ]; then
    ack-grep -i "$@"
else
    ack -i "$@"
fi
