#!/usr/bin/env bash

# Quick search in a directory for a stringj
# Author: Nkululeko Jonas
# Lincense: Nkululeko Jonas

# use -iru to search directories ack usually ignores (like .git)
if [ -x /usr/bin/ack-grep ]; then
    ack-grep -i "$@"
else
    ack -i "$@"
fi
