#!/bin/bash

# search: search a directory for a string
# Author: Nkululeko Jonas
# License: MIT

# use -iru to search directories ack usually ignores (like .git)
if [ -x /usr/bin/ack-grep ]; then
    ack-grep -i "$@"
else
    ack -i "$@"
fi
